export const IMG_CDN_URL =
  "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";

export const SWIGGY_API_URL =
  "https://www.swiggy.com/dapi/restaurants/list/v5?lat=21.1702401&lng=72.83106070000001&page_type=DESKTOP_WEB_LISTING";
// export const restaurantlist = [
//     {
//       type: "restaurant",
//       data: {
//         type: "F",
//         id: "476595",
//         name: "Chicking",
//         uuid: "1869ec00-cd94-4954-b688-0dfcc9cc610e",
//         city: "162",
//         area: "Kollam City",
//         totalRatingsString: "1000+ ratings",
//         cloudinaryImageId: "mlons1xzi7kfuqkaqejy",
//         cuisines: ["Burgers", "Pizzas"],
//         tags: [],
//         costForTwo: 50000,
//         costForTwoString: "₹500 FOR TWO",
//         deliveryTime: 30,
//         minDeliveryTime: 30,
//         maxDeliveryTime: 30,
//         slaString: "30 MINS",
//         lastMileTravel: 1.100000023841858,
//         slugs: {
//           restaurant: "chicking-kollam-city-kollam-city",
//           city: "kollam",
//         },
//         cityState: "162",
//         address: "Chicking  Sans buliding  Kottiyam jn  Near I mall, Kollam",
//         locality: "Kollam City",
//         parentId: 251,
//         unserviceable: false,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         aggregatedDiscountInfo: {
//           header: "40% off",
//           shortDescriptionList: [
//             {
//               meta: "40% off | Use TRYNEW",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "40% off up to ₹80 | Use code TRYNEW",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         aggregatedDiscountInfoV2: {
//           header: "40% OFF",
//           shortDescriptionList: [
//             {
//               meta: "Use TRYNEW",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "40% off up to ₹80 | Use code TRYNEW",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         ribbon: [
//           {
//             type: "PROMOTED",
//           },
//         ],
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 1900,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 1900,
//           message: "",
//           title: "Delivery Charge",
//           amount: "1900",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "cid=5676718~p=1~eid=00000185-bf29-5391-01c0-ba8300e40124",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "1.1 kms",
//         hasSurge: false,
//         sla: {
//           restaurantId: "476595",
//           deliveryTime: 30,
//           minDeliveryTime: 30,
//           maxDeliveryTime: 30,
//           lastMileTravel: 1.100000023841858,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: true,
//         avgRating: "4.1",
//         totalRatings: 1000,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurant",
//       data: {
//         type: "F",
//         id: "176963",
//         name: "Hotel Nice",
//         uuid: "42f7b73a-fad3-49b3-910f-5cc12233de07",
//         city: "162",
//         area: "Kottiyam Juntion",
//         totalRatingsString: "10000+ ratings",
//         cloudinaryImageId: "btdmyfrtih7mwt5gcpju",
//         cuisines: ["Chinese", "North Indian", "South Indian", "Biryani"],
//         tags: [],
//         costForTwo: 20000,
//         costForTwoString: "₹200 FOR TWO",
//         deliveryTime: 15,
//         minDeliveryTime: 15,
//         maxDeliveryTime: 15,
//         slaString: "15 MINS",
//         lastMileTravel: 1.100000023841858,
//         slugs: {
//           restaurant: "hotel-nice-kottiyam-kollam-city",
//           city: "kollam",
//         },
//         cityState: "162",
//         address: "Kottiyam, Kerala 695171",
//         locality: "Kottiyam",
//         parentId: 100766,
//         unserviceable: false,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         aggregatedDiscountInfo: {
//           header: "60% off",
//           shortDescriptionList: [
//             {
//               meta: "60% off | Use MISSEDYOU",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "60% off up to ₹120 | Use code MISSEDYOU",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         aggregatedDiscountInfoV2: {
//           header: "60% OFF",
//           shortDescriptionList: [
//             {
//               meta: "Use MISSEDYOU",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "60% off up to ₹120 | Use code MISSEDYOU",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 1900,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 1900,
//           message: "",
//           title: "Delivery Charge",
//           amount: "1900",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "1.1 kms",
//         hasSurge: false,
//         sla: {
//           restaurantId: "176963",
//           deliveryTime: 15,
//           minDeliveryTime: 15,
//           maxDeliveryTime: 15,
//           lastMileTravel: 1.100000023841858,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "3.8",
//         totalRatings: 10000,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurant",
//       data: {
//         type: "F",
//         id: "132384",
//         name: "Ramees Restaurant",
//         uuid: "fa86028b-b5c3-4033-bb68-4aea9377090b",
//         city: "162",
//         area: "Kottiyam Juntion",
//         totalRatingsString: "5000+ ratings",
//         cloudinaryImageId: "peqphhiuh8xmmpq2iebt",
//         cuisines: ["Chinese", "North Indian", "South Indian", "Ice Cream"],
//         tags: [],
//         costForTwo: 40000,
//         costForTwoString: "₹400 FOR TWO",
//         deliveryTime: 24,
//         minDeliveryTime: 24,
//         maxDeliveryTime: 24,
//         slaString: "24 MINS",
//         lastMileTravel: 1.2999999523162842,
//         slugs: {
//           restaurant: "ramees-restaurant-chinnakada-ms-nagar",
//           city: "kollam",
//         },
//         cityState: "162",
//         address:
//           "19/889 RAMEES RESTAURANT AND CATERERS TRIVANDRUM ROAD KOTTIYAM KOLLAM  , Chathannoor Circle, Kollam, Kerala-691571",
//         locality: "Kottiyam",
//         parentId: 19986,
//         unserviceable: false,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         aggregatedDiscountInfo: {
//           header: "40% off",
//           shortDescriptionList: [
//             {
//               meta: "40% off | Use MISSEDYOU",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "40% off up to ₹80 | Use code MISSEDYOU",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         aggregatedDiscountInfoV2: {
//           header: "40% OFF",
//           shortDescriptionList: [
//             {
//               meta: "Use MISSEDYOU",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "40% off up to ₹80 | Use code MISSEDYOU",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 1900,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 1900,
//           message: "",
//           title: "Delivery Charge",
//           amount: "1900",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "1.2 kms",
//         hasSurge: false,
//         sla: {
//           restaurantId: "132384",
//           deliveryTime: 24,
//           minDeliveryTime: 24,
//           maxDeliveryTime: 24,
//           lastMileTravel: 1.2999999523162842,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "4.1",
//         totalRatings: 5000,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurant",
//       data: {
//         type: "F",
//         id: "432398",
//         name: "Qahwa Restaurant",
//         uuid: "6b75cb43-3f8e-488b-a406-f4b358066a4c",
//         city: "162",
//         area: "Karikode",
//         totalRatingsString: "1000+ ratings",
//         cloudinaryImageId: "osyrtp80cmzoqkjpo5dq",
//         cuisines: ["North Indian", "Burgers", "Ice Cream"],
//         tags: [],
//         costForTwo: 29900,
//         costForTwoString: "₹299 FOR TWO",
//         deliveryTime: 33,
//         minDeliveryTime: 33,
//         maxDeliveryTime: 33,
//         slaString: "33 MINS",
//         lastMileTravel: 7.900000095367432,
//         slugs: {
//           restaurant: "qahwa-restaurant-kollam-city-kollam-city",
//           city: "kollam",
//         },
//         cityState: "162",
//         address:
//           "JASIN ARCADE,KARICODE, Kundara Circle,  Kollam, Kerala - 691005",
//         locality: "Karikode",
//         parentId: 260724,
//         unserviceable: false,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         aggregatedDiscountInfo: {
//           header: "50% off",
//           shortDescriptionList: [
//             {
//               meta: "50% off | Use TRYNEW",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "50% off up to ₹100 | Use code TRYNEW",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         aggregatedDiscountInfoV2: {
//           header: "50% OFF",
//           shortDescriptionList: [
//             {
//               meta: "Use TRYNEW",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "50% off up to ₹100 | Use code TRYNEW",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         ribbon: [
//           {
//             type: "PROMOTED",
//           },
//         ],
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 3400,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 3400,
//           message: "",
//           title: "Delivery Charge",
//           amount: "3400",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "cid=5676723~p=4~eid=00000185-bf29-5391-01c0-ba8400e4040f",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "7.9 kms",
//         hasSurge: false,
//         sla: {
//           restaurantId: "432398",
//           deliveryTime: 33,
//           minDeliveryTime: 33,
//           maxDeliveryTime: 33,
//           lastMileTravel: 7.900000095367432,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: true,
//         avgRating: "4.1",
//         totalRatings: 1000,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurant",
//       data: {
//         type: "F",
//         id: "177565",
//         name: "Hot Cakes Bakery & Restaurant",
//         uuid: "22464185-14af-4c91-b635-3aeddb362e58",
//         city: "162",
//         area: "Kottiyam Juntion",
//         totalRatingsString: "1000+ ratings",
//         cloudinaryImageId: "xkk6lt4xbcwywvj0qnkt",
//         cuisines: ["Desserts", "Chinese", "South Indian", "Burgers", "Ice Cream"],
//         tags: [],
//         costForTwo: 35000,
//         costForTwoString: "₹350 FOR TWO",
//         deliveryTime: 24,
//         minDeliveryTime: 24,
//         maxDeliveryTime: 24,
//         slaString: "24 MINS",
//         lastMileTravel: 1.100000023841858,
//         slugs: {
//           restaurant: "hot-cakes-bakery-restauramt-kottiyam-kottiyam",
//           city: "kollam",
//         },
//         cityState: "162",
//         address:
//           "opp dhanya supermarket, selam, Srinagar - Kanyakumari Hwy, Kottiyam, Kerala 691571",
//         locality: "Kottiyam",
//         parentId: 97198,
//         unserviceable: false,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         aggregatedDiscountInfo: {
//           header: "30% off",
//           shortDescriptionList: [
//             {
//               meta: "30% off | Use TRYNEW",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "30% off up to ₹75 | Use code TRYNEW",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         aggregatedDiscountInfoV2: {
//           header: "30% OFF",
//           shortDescriptionList: [
//             {
//               meta: "Use TRYNEW",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "30% off up to ₹75 | Use code TRYNEW",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 1900,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 1900,
//           message: "",
//           title: "Delivery Charge",
//           amount: "1900",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "1.1 kms",
//         hasSurge: false,
//         sla: {
//           restaurantId: "177565",
//           deliveryTime: 24,
//           minDeliveryTime: 24,
//           maxDeliveryTime: 24,
//           lastMileTravel: 1.100000023841858,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "4.2",
//         totalRatings: 1000,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurant",
//       data: {
//         type: "F",
//         id: "177560",
//         name: "Hot Cakes Bakery & Juice",
//         uuid: "97c0e257-15ba-42f3-9879-cbfcb2270d85",
//         city: "162",
//         area: "Kottiyam",
//         totalRatingsString: "1000+ ratings",
//         cloudinaryImageId: "xzpjnuiwexexpxhxnaom",
//         cuisines: ["Desserts", "South Indian", "Burgers", "Ice Cream"],
//         tags: [],
//         costForTwo: 15000,
//         costForTwoString: "₹150 FOR TWO",
//         deliveryTime: 19,
//         minDeliveryTime: 19,
//         maxDeliveryTime: 19,
//         slaString: "19 MINS",
//         lastMileTravel: 0.699999988079071,
//         slugs: {
//           restaurant: "hot-cakes-bakery-juice-kottiyam-kottiyam",
//           city: "kollam",
//         },
//         cityState: "162",
//         address: "Kottiyam Kerala",
//         locality: "Kottiyam",
//         parentId: 97197,
//         unserviceable: false,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         aggregatedDiscountInfo: {
//           header: "30% off",
//           shortDescriptionList: [
//             {
//               meta: "30% off | Use TRYNEW",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "30% off up to ₹75 | Use code TRYNEW",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         aggregatedDiscountInfoV2: {
//           header: "30% OFF",
//           shortDescriptionList: [
//             {
//               meta: "Use TRYNEW",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "30% off up to ₹75 | Use code TRYNEW",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 1900,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 1900,
//           message: "",
//           title: "Delivery Charge",
//           amount: "1900",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "0.6 kms",
//         hasSurge: false,
//         sla: {
//           restaurantId: "177560",
//           deliveryTime: 19,
//           minDeliveryTime: 19,
//           maxDeliveryTime: 19,
//           lastMileTravel: 0.699999988079071,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "4.1",
//         totalRatings: 1000,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurant",
//       data: {
//         type: "F",
//         id: "419858",
//         name: "Secret Spice",
//         uuid: "5beafbbb-0f39-4f71-bcb1-373ceccfbcc7",
//         city: "162",
//         area: "Kollam City",
//         totalRatingsString: "100+ ratings",
//         cloudinaryImageId: "zmvigl2lvvd8uo0dbbmp",
//         cuisines: ["Burgers", "Pizzas"],
//         tags: [],
//         costForTwo: 19900,
//         costForTwoString: "₹199 FOR TWO",
//         deliveryTime: 39,
//         minDeliveryTime: 39,
//         maxDeliveryTime: 39,
//         slaString: "39 MINS",
//         lastMileTravel: 0.5,
//         slugs: {
//           restaurant: "secret-spice-kollam-city-kollam-city",
//           city: "kollam",
//         },
//         cityState: "162",
//         address:
//           "Secret spice, opp olippil complex, kannanalloor road, kottiyam po, kollam",
//         locality: "Kannanalloor Road",
//         parentId: 179789,
//         unserviceable: false,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 1900,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 1900,
//           message: "",
//           title: "Delivery Charge",
//           amount: "1900",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "0.5 kms",
//         hasSurge: false,
//         sla: {
//           restaurantId: "419858",
//           deliveryTime: 39,
//           minDeliveryTime: 39,
//           maxDeliveryTime: 39,
//           lastMileTravel: 0.5,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "3.6",
//         totalRatings: 100,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurant",
//       data: {
//         type: "F",
//         id: "383506",
//         name: "Salwa Super Chef",
//         uuid: "65b092ce-71cc-4ead-8246-da815e1219b8",
//         city: "162",
//         area: "Kollam City",
//         totalRatingsString: "1000+ ratings",
//         cloudinaryImageId: "qhgwnamzlw0fdwjlm2r8",
//         cuisines: ["Chinese", "North Indian", "South Indian"],
//         tags: [],
//         costForTwo: 11000,
//         costForTwoString: "₹110 FOR TWO",
//         deliveryTime: 21,
//         minDeliveryTime: 21,
//         maxDeliveryTime: 21,
//         slaString: "21 MINS",
//         lastMileTravel: 2.299999952316284,
//         slugs: {
//           restaurant: "salwa-super-chef-kollam-city-kollam-city",
//           city: "kollam",
//         },
//         cityState: "162",
//         address: "Salwa Super Chef, Umayanalloor, Eravipuram circle, kollam",
//         locality: "Umayanalloor",
//         parentId: 254341,
//         unserviceable: false,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 1900,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 1900,
//           message: "",
//           title: "Delivery Charge",
//           amount: "1900",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "2.2 kms",
//         hasSurge: false,
//         sla: {
//           restaurantId: "383506",
//           deliveryTime: 21,
//           minDeliveryTime: 21,
//           maxDeliveryTime: 21,
//           lastMileTravel: 2.299999952316284,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "4.2",
//         totalRatings: 1000,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurant",
//       data: {
//         type: "F",
//         id: "183468",
//         name: "Hotel Bright",
//         uuid: "5211af66-a907-43b5-9f82-5587e2e7c853",
//         city: "162",
//         area: "Kottiyam Juntion",
//         totalRatingsString: "1000+ ratings",
//         cloudinaryImageId: "luivvdnbxnbny6xcduij",
//         cuisines: ["Chinese", "North Indian", "South Indian", "Biryani"],
//         tags: [],
//         costForTwo: 60000,
//         costForTwoString: "₹600 FOR TWO",
//         deliveryTime: 18,
//         minDeliveryTime: 18,
//         maxDeliveryTime: 18,
//         slaString: "18 MINS",
//         lastMileTravel: 0.8999999761581421,
//         slugs: {
//           restaurant: "hotel-bright-kottiyam-kottiyam-kottiyam",
//           city: "kollam",
//         },
//         cityState: "162",
//         address: "NH 66, Kottiyam, Kerala 691571",
//         locality: "Kottiyam",
//         parentId: 98440,
//         unserviceable: false,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 1900,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 1900,
//           message: "",
//           title: "Delivery Charge",
//           amount: "1900",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "0.8 kms",
//         hasSurge: false,
//         sla: {
//           restaurantId: "183468",
//           deliveryTime: 18,
//           minDeliveryTime: 18,
//           maxDeliveryTime: 18,
//           lastMileTravel: 0.8999999761581421,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "3.9",
//         totalRatings: 1000,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurant",
//       data: {
//         type: "F",
//         id: "636670",
//         name: "Tasty And Crispy",
//         uuid: "f3fb0689-3661-4e65-9c72-6a90190c2e1d",
//         city: "162",
//         area: "Kollam City",
//         totalRatingsString: "Too Few Ratings",
//         cloudinaryImageId: "xyl3drlggeyfg0l0nt4q",
//         cuisines: ["Burgers", "Snacks"],
//         tags: [],
//         costForTwo: 30000,
//         costForTwoString: "₹300 FOR TWO",
//         deliveryTime: 30,
//         minDeliveryTime: 30,
//         maxDeliveryTime: 30,
//         slaString: "30 MINS",
//         lastMileTravel: 1,
//         slugs: {
//           restaurant: "tasty-and-crispy-kollam-city-kollam-city",
//           city: "kollam",
//         },
//         cityState: "162",
//         address:
//           "TASTY AND CRISPY, KOTTIYAM, Eravipuram Circle, Kollam, Kerala- 691571",
//         locality: "Eravipuram Circle",
//         parentId: 384488,
//         unserviceable: false,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 1900,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 1900,
//           message: "",
//           title: "Delivery Charge",
//           amount: "1900",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "1 kms",
//         hasSurge: false,
//         sla: {
//           restaurantId: "636670",
//           deliveryTime: 30,
//           minDeliveryTime: 30,
//           maxDeliveryTime: 30,
//           lastMileTravel: 1,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "--",
//         totalRatings: 0,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurant",
//       data: {
//         type: "F",
//         id: "162527",
//         name: "AL Hayat Mevaram",
//         uuid: "d4d3c6df-1b03-4321-a741-075e8dc7ce73",
//         city: "162",
//         area: "Palathara",
//         totalRatingsString: "5000+ ratings",
//         cloudinaryImageId: "an0uiqgw9ovohdhyrxvr",
//         cuisines: [
//           "Chinese",
//           "North Indian",
//           "South Indian",
//           "Ice Cream",
//           "Biryani",
//         ],
//         tags: [],
//         costForTwo: 30000,
//         costForTwoString: "₹300 FOR TWO",
//         deliveryTime: 24,
//         minDeliveryTime: 24,
//         maxDeliveryTime: 24,
//         slaString: "24 MINS",
//         lastMileTravel: 4.300000190734863,
//         slugs: {
//           restaurant: "al-hayat-mevaram-mevaram-kollam-city",
//           city: "kollam",
//         },
//         cityState: "162",
//         address: "Mevaram, kollam pin 691020",
//         locality: "Mevaram",
//         parentId: 29145,
//         unserviceable: false,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         aggregatedDiscountInfo: {
//           header: "30% off",
//           shortDescriptionList: [
//             {
//               meta: "30% off | Use MISSEDYOU",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "30% off up to ₹75 | Use code MISSEDYOU",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         aggregatedDiscountInfoV2: {
//           header: "30% OFF",
//           shortDescriptionList: [
//             {
//               meta: "Use MISSEDYOU",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "30% off up to ₹75 | Use code MISSEDYOU",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 1900,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 1900,
//           message: "",
//           title: "Delivery Charge",
//           amount: "1900",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "4.3 kms",
//         hasSurge: false,
//         sla: {
//           restaurantId: "162527",
//           deliveryTime: 24,
//           minDeliveryTime: 24,
//           maxDeliveryTime: 24,
//           lastMileTravel: 4.300000190734863,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "4.1",
//         totalRatings: 5000,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurant",
//       data: {
//         type: "F",
//         id: "623948",
//         name: "ABOOS Restaurant",
//         uuid: "d43ce605-cf7d-40af-a549-a41909df69ff",
//         city: "162",
//         area: "Kollam City",
//         totalRatingsString: "Too Few Ratings",
//         cloudinaryImageId: "raeqosopuwz4sm7hwmn7",
//         cuisines: ["Chinese", "South Indian", "Snacks"],
//         tags: [],
//         costForTwo: 20000,
//         costForTwoString: "₹200 FOR TWO",
//         deliveryTime: 28,
//         minDeliveryTime: 28,
//         maxDeliveryTime: 28,
//         slaString: "28 MINS",
//         lastMileTravel: 1.600000023841858,
//         slugs: {
//           restaurant: "aboos-restaurant-kollam-city-kollam-city",
//           city: "kollam",
//         },
//         cityState: "162",
//         address: "VM7H+XHW, Kottiyam, Kerala 691571, India",
//         locality: "Kottiyam",
//         parentId: 371114,
//         unserviceable: false,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 1900,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 1900,
//           message: "",
//           title: "Delivery Charge",
//           amount: "1900",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "1.6 kms",
//         hasSurge: false,
//         sla: {
//           restaurantId: "623948",
//           deliveryTime: 28,
//           minDeliveryTime: 28,
//           maxDeliveryTime: 28,
//           lastMileTravel: 1.600000023841858,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "--",
//         totalRatings: 0,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurant",
//       data: {
//         type: "F",
//         id: "133084",
//         name: "A1 Kuzhimandhi",
//         uuid: "f0508986-d60f-4c6b-a33a-f38d9e9550e4",
//         city: "162",
//         area: "Mevaram",
//         totalRatingsString: "500+ ratings",
//         cloudinaryImageId: "lw8m3ugecbhrkzljea5r",
//         cuisines: ["Arabian", "Mangalorean"],
//         tags: [],
//         costForTwo: 28000,
//         costForTwoString: "₹280 FOR TWO",
//         deliveryTime: 30,
//         minDeliveryTime: 30,
//         maxDeliveryTime: 30,
//         slaString: "30 MINS",
//         lastMileTravel: 4.099999904632568,
//         slugs: {
//           restaurant: "a1-kuzhi-mandhi-chinnakada-ms-nagar",
//           city: "kollam",
//         },
//         cityState: "162",
//         address: "Vazhapally,kollam",
//         locality: "Chinnakada",
//         parentId: 25136,
//         unserviceable: false,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 1900,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 1900,
//           message: "",
//           title: "Delivery Charge",
//           amount: "1900",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "4 kms",
//         hasSurge: false,
//         sla: {
//           restaurantId: "133084",
//           deliveryTime: 30,
//           minDeliveryTime: 30,
//           maxDeliveryTime: 30,
//           lastMileTravel: 4.099999904632568,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "3.7",
//         totalRatings: 500,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurant",
//       data: {
//         type: "F",
//         id: "176950",
//         name: "Just Cakes",
//         uuid: "4e6fdf76-2cdd-4a6a-bfb5-93713b3e1b56",
//         city: "162",
//         area: "Mayyanad",
//         totalRatingsString: "100+ ratings",
//         cloudinaryImageId: "sxwibnfsmuyvcsipynkv",
//         cuisines: ["Bakery", "Arabian"],
//         tags: [],
//         costForTwo: 25000,
//         costForTwoString: "₹250 FOR TWO",
//         deliveryTime: 27,
//         minDeliveryTime: 27,
//         maxDeliveryTime: 27,
//         slaString: "27 MINS",
//         lastMileTravel: 2.700000047683716,
//         slugs: {
//           restaurant: "just-cakes-umayanallor-kollam-city",
//           city: "kollam",
//         },
//         cityState: "162",
//         address:
//           "NS Complex, Opposite Brothers Auditorium,Umayanalloor, Kerala 691589",
//         locality: "Umayanalloor",
//         parentId: 112330,
//         unserviceable: false,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 1900,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 1900,
//           message: "",
//           title: "Delivery Charge",
//           amount: "1900",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "2.7 kms",
//         hasSurge: false,
//         sla: {
//           restaurantId: "176950",
//           deliveryTime: 27,
//           minDeliveryTime: 27,
//           maxDeliveryTime: 27,
//           lastMileTravel: 2.700000047683716,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "3.7",
//         totalRatings: 100,
//         new: false,
//       },
//       subtype: "basic",
//     },
//     {
//       type: "restaurant",
//       data: {
//         type: "F",
//         id: "343743",
//         name: "Le Chique",
//         uuid: "c54556b7-1d99-42dc-a46e-05e7da3abdbb",
//         city: "162",
//         area: "Ayathil",
//         totalRatingsString: "5000+ ratings",
//         cloudinaryImageId: "oxycaeptd1bies8gdjyt",
//         cuisines: ["Chinese", "North Indian", "South Indian", "Biryani"],
//         tags: [],
//         costForTwo: 30000,
//         costForTwoString: "₹300 FOR TWO",
//         deliveryTime: 25,
//         minDeliveryTime: 25,
//         maxDeliveryTime: 25,
//         slaString: "25 MINS",
//         lastMileTravel: 5.5,
//         slugs: {
//           restaurant: "le-chique-kollam-city-kollam-city",
//           city: "kollam",
//         },
//         cityState: "162",
//         address:
//           "LE CHIQUE, DOOR NO 31/1346-1347, NEAR AL MANAMA SUPER MARKET PUNTHALATHAZHAM KILIKOLLOOR PO, KOLLAM",
//         locality: "Kollam City",
//         parentId: 124460,
//         unserviceable: false,
//         veg: false,
//         select: false,
//         favorite: false,
//         tradeCampaignHeaders: [],
//         aggregatedDiscountInfo: {
//           header: "60% off",
//           shortDescriptionList: [
//             {
//               meta: "60% off | Use TRYNEW",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "60% off up to ₹120 | Use code TRYNEW",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         aggregatedDiscountInfoV2: {
//           header: "60% OFF",
//           shortDescriptionList: [
//             {
//               meta: "Use TRYNEW",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           descriptionList: [
//             {
//               meta: "60% off up to ₹120 | Use code TRYNEW",
//               discountType: "Percentage",
//               operationType: "RESTAURANT",
//             },
//           ],
//           subHeader: "",
//           headerType: 0,
//           superFreedel: "",
//         },
//         chain: [],
//         feeDetails: {
//           fees: [
//             {
//               name: "distance",
//               fee: 2400,
//               message: "",
//             },
//             {
//               name: "time",
//               fee: 0,
//               message: "",
//             },
//             {
//               name: "special",
//               fee: 0,
//               message: "",
//             },
//           ],
//           totalFees: 2400,
//           message: "",
//           title: "Delivery Charge",
//           amount: "2400",
//           icon: "",
//         },
//         availability: {
//           opened: true,
//           nextOpenMessage: "",
//           nextCloseMessage: "",
//         },
//         longDistanceEnabled: 0,
//         rainMode: "NONE",
//         thirdPartyAddress: false,
//         thirdPartyVendor: "",
//         adTrackingID: "",
//         badges: {
//           imageBased: [],
//           textBased: [],
//           textExtendedBadges: [],
//         },
//         lastMileTravelString: "5.5 kms",
//         hasSurge: false,
//         sla: {
//           restaurantId: "343743",
//           deliveryTime: 25,
//           minDeliveryTime: 25,
//           maxDeliveryTime: 25,
//           lastMileTravel: 5.5,
//           lastMileDistance: 0,
//           serviceability: "SERVICEABLE",
//           rainMode: "NONE",
//           longDistance: "NOT_LONG_DISTANCE",
//           preferentialService: false,
//           iconType: "EMPTY",
//         },
//         promoted: false,
//         avgRating: "3.7",
//         totalRatings: 5000,
//         new: false,
//       },
//       subtype: "basic",
//     },
//   ];
